package com.modsocial.app;

import android.app.*;
import android.os.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import android.text.InputType;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;
import java.text.SimpleDateFormat;

public final class MainActivity extends Activity {
 private static final int INK=0xff20251e,BG=0xfff8faf6,LIME=0xffc7ff55,MUTED=0xff72776e;
 private final ExecutorService io=Executors.newSingleThreadExecutor();
 private final Handler clock=new Handler(Looper.getMainLooper());
 private final Runnable refreshClock=()->{if(!isFinishing()){render();scheduleClock();}};
 private Store store;private Session session;private JSONObject state;
 private String token="",base="",view="feed",filter="all";private boolean remote=false,busy=false;
 private LinearLayout root,body;private ScrollView scroll;
 private final String[] keys={"coffee","walk","music","game"},moods={"☕ Kahve","🚶 Yürüyüş","🎵 Müzik","🎮 Oyun"};
 private int dp(float n){return (int)(getResources().getDisplayMetrics().density*n+.5f);}
 @Override public void onCreate(Bundle saved){super.onCreate(saved);store=new Store(this);session=new Session(this);base=BuildConfig.API_BASE_URL.isEmpty()?getPreferences(0).getString("server",""):BuildConfig.API_BASE_URL;token=session.load();remote=!token.isEmpty()&&!base.isEmpty();
  try{state=remote?emptyState():store.load();}catch(Exception e){state=new JSONObject();}
  if(saved!=null){view=saved.getString("view","feed");filter=saved.getString("filter","all");}
  getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(Color.WHITE);
  getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
  render();if(remote)reload();
 }
 @Override protected void onResume(){super.onResume();scheduleClock();}
 @Override protected void onPause(){super.onPause();clock.removeCallbacks(refreshClock);}
 private void scheduleClock(){clock.removeCallbacks(refreshClock);clock.postDelayed(refreshClock,60000);}
 @Override protected void onDestroy(){super.onDestroy();io.shutdownNow();clock.removeCallbacks(refreshClock);}
 @Override protected void onSaveInstanceState(Bundle b){b.putString("view",view);b.putString("filter",filter);super.onSaveInstanceState(b);}
 private JSONObject emptyState()throws JSONException{return new JSONObject().put("me",Store.user("","Hesabın","")).put("users",new JSONArray()).put("plans",new JSONArray()).put("following",new JSONArray()).put("joined",new JSONArray());}
 private GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
 private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 private TextView text(String t,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(t);v.setTextSize(size);v.setTextColor(color);v.setLineSpacing(dp(2),1);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
 private void gap(LinearLayout l,int h){View v=new View(this);l.addView(v,new LinearLayout.LayoutParams(1,dp(h)));}
 private Button button(String title,int color,Runnable action){Button b=new Button(this);b.setText(title);b.setTextSize(14);b.setAllCaps(false);b.setTextColor(INK);b.setMinHeight(dp(48));b.setMinimumHeight(dp(48));b.setPadding(dp(14),dp(5),dp(14),dp(5));b.setBackground(shape(color,14));b.setOnClickListener(v->{if(!busy)action.run();});return b;}
 private void wide(LinearLayout l,View v){l.addView(v,new LinearLayout.LayoutParams(-1,-2));}
 private void msg(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 private JSONArray arr(String key){return state.optJSONArray(key)==null?new JSONArray():state.optJSONArray(key);}
 private JSONObject me(){return state.optJSONObject("me")==null?new JSONObject():state.optJSONObject("me");}
 private boolean has(String key,String id){return Store.contains(arr(key),id);}
 private JSONObject user(String id){if(id.equals(me().optString("id")))return me();for(int i=0;i<arr("users").length();i++){JSONObject u=arr("users").optJSONObject(i);if(u!=null&&id.equals(u.optString("id")))return u;}return new JSONObject();}
 private String mood(String type){for(int i=0;i<keys.length;i++)if(keys[i].equals(type))return moods[i];return "Plan";}
 private String date(long ms){return new SimpleDateFormat("d MMM · HH:mm",new Locale("tr","TR")).format(new Date(ms));}
 private void render(){if(isFinishing())return;root=col();root.setBackgroundColor(BG);root.setPadding(dp(18),0,dp(18),0);
  root.setOnApplyWindowInsetsListener((v,in)->{v.setPadding(dp(18),in.getSystemWindowInsetTop(),dp(18),in.getSystemWindowInsetBottom());return in;});setContentView(root);root.requestApplyInsets();
  LinearLayout top=row();TextView logo=text("mod•",36,INK,true);top.addView(logo,new LinearLayout.LayoutParams(0,dp(66),1));Button account=button(remote?"Hesabım":"Hesaba bağlan",0xffe9efdf,()->{if(remote){view="profile";render();}else authDialog();});top.addView(account);wide(root,top);
  scroll=new ScrollView(this);scroll.setFillViewport(true);body=col();body.setPadding(0,dp(12),0,dp(24));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  String title=view.equals("feed")?"Bugün hangi moddasın?":view.equals("explore")?"Aynı modda buluşalım.":view.equals("plans")?"Birlikte planlarımız.":"Senin köşen.";
  wide(body,text(title,28,INK,true));gap(body,8);wide(body,text(remote?"Gerçek hesap · "+me().optString("city",""):"Cihaz demosu · Örnek kişiler, kalıcı yerel kayıt",12,MUTED,false));gap(body,20);
  if(busy){ProgressBar progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setIndeterminate(true);wide(body,progress);gap(body,12);}
  if(view.equals("profile"))profile();
  wide(body,button("＋  Birlikte ne yapalım?",LIME,this::compose));gap(body,22);
  if(view.equals("feed")||view.equals("explore")){HorizontalScrollView h=new HorizontalScrollView(this);h.setHorizontalScrollBarEnabled(false);LinearLayout chips=row();addChip(chips,"all","Tümü");for(int i=0;i<keys.length;i++)addChip(chips,keys[i],moods[i]);h.addView(chips);wide(body,h);gap(body,20);}
  if(view.equals("explore")){wide(body,text("Tanışabileceğin kişiler",18,INK,true));gap(body,10);for(int i=0;i<arr("users").length();i++)personRow(arr("users").optJSONObject(i));gap(body,20);}
  wide(body,text(view.equals("feed")?"Takip ettiğin kişilerin planları":view.equals("profile")?"Paylaştığın planlar":"Aktif planlar",18,INK,true));gap(body,14);
  int visible=0;for(int i=0;i<arr("plans").length();i++){JSONObject p=arr("plans").optJSONObject(i);if(p==null||p.optLong("expires_at")<=System.currentTimeMillis())continue;String owner=p.optString("user_id");boolean own=owner.equals(me().optString("id"));if(view.equals("feed")&&!own&&!has("following",owner))continue;if(view.equals("plans")&&!own&&!has("joined",p.optString("id")))continue;if(view.equals("profile")&&!own)continue;if((view.equals("feed")||view.equals("explore"))&&!filter.equals("all")&&!filter.equals(p.optString("type")))continue;card(p);visible++;}
  if(visible==0){wide(body,text("Henüz bir plan yok.",20,INK,true));gap(body,6);wide(body,text("Yeni bir plan paylaş veya Keşfet’ten birine katıl.",15,MUTED,false));}
  gap(root,8);LinearLayout nav=row();String[] views={"feed","explore","plans","profile"},labels={"⌂\nAkış","◎\nKeşfet","▦\nPlanlarım","◉\nProfil"};for(int i=0;i<views.length;i++){final String dest=views[i];Button b=button(labels[i],view.equals(dest)?0xffe7f2da:Color.WHITE,()->{view=dest;filter="all";render();});b.setTextSize(12);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(62),1);lp.setMargins(dp(2),0,dp(2),dp(8));nav.addView(b,lp);}wide(root,nav);
 }
 private void addChip(LinearLayout l,String key,String label){Button b=button(label,filter.equals(key)?LIME:Color.WHITE,()->{filter=key;render();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,dp(48));lp.setMargins(0,0,dp(8),0);l.addView(b,lp);}
 private void personRow(JSONObject u){if(u==null)return;LinearLayout r=row();r.addView(text(u.optString("name"),16,INK,true),new LinearLayout.LayoutParams(0,-2,1));r.addView(button(has("following",u.optString("id"))?"Takiptesin":"Takip et",0xffeaf1e1,()->follow(u.optString("id"))));wide(body,r);gap(body,8);}
 private void card(JSONObject p){String id=p.optString("id"),owner=p.optString("user_id");boolean own=owner.equals(me().optString("id"));JSONObject u=user(owner);LinearLayout c=col();c.setPadding(dp(18),dp(18),dp(18),dp(18));c.setBackground(shape(Color.WHITE,22));
  LinearLayout heading=row();TextView name=text(u.optString("name","Kullanıcı"),16,INK,true);heading.addView(name,new LinearLayout.LayoutParams(0,-2,1));if(!own)heading.addView(button(has("following",owner)?"Takiptesin":"Takip et",0xffeef3e8,()->follow(owner)));wide(c,heading);gap(c,10);
  wide(c,text(mood(p.optString("type")),14,0xff567332,true));gap(c,12);wide(c,text(p.optString("title"),22,INK,true));gap(c,10);wide(c,text("◷ "+date(p.optLong("starts_at"))+"\n⌖ "+p.optString("place"),14,MUTED,false));gap(c,8);
  String a=p.optString("audience");wide(c,text(a.equals("followers")?"Takipçilere açık":a.equals("private")?"Yalnızca ben":"Herkese açık",12,MUTED,false));gap(c,16);
  LinearLayout bottom=row();int count=p.optInt("count")+(!remote&&has("joined",id)?1:0);bottom.addView(text(count+" kişi aynı modda",13,MUTED,false),new LinearLayout.LayoutParams(0,-2,1));bottom.addView(button(own?"Kaldır":has("joined",id)?"✓ Katıldın":"Ben de +",LIME,()->{if(own)confirmDelete(id);else join(id);}));wide(c,bottom);if(remote&&!own){gap(c,10);wide(c,button("Şikâyet et / Engelle",0xfff1f3ef,()->safetyMenu(p)));}wide(body,c);gap(body,16);
 }
 private void profile(){wide(body,text(me().optString("name","Engin"),24,INK,true));wide(body,text(me().optString("city","Mersin")+" · "+arr("following").length()+" takip edilen",15,MUTED,false));gap(body,12);wide(body,button("Profili düzenle",0xffe9efdf,this::editProfile));gap(body,8);
  if(remote){wide(body,button("Yenile",0xffe9efdf,this::reload));gap(body,8);wide(body,button("Çıkış yap",0xffe9efdf,()->logout()));gap(body,8);wide(body,button("Hesabımı sil",0xfff8e7e5,()->new AlertDialog.Builder(this).setTitle("Hesap silinsin mi?").setMessage("Profilin, planların ve katılımların kalıcı olarak silinir.").setNegativeButton("Vazgeç",null).setPositiveButton("Hesabımı sil",(d,w)->request("DELETE","/account",null,r->disconnect())).show()));}else{wide(body,text("Bu profil sadece bu telefonda saklanır. Gerçek kullanıcılarla paylaşmak için bir MOD sunucusuna bağlanmalısın.",14,MUTED,false));}
  if(remote){gap(body,8);wide(body,button("Engellediğim kişiler",0xffe9efdf,this::showBlocked));gap(body,8);wide(body,button("Topluluk kuralları",0xffe9efdf,this::showTerms));}gap(body,24);
 }
 private static final String RULES="MOD'da tehdit, taciz, nefret söylemi, dolandırıcılık, spam, yasa dışı faaliyet ve kişisel bilgilerin izinsiz paylaşımı yasaktır. Çocuklara yönelik cinsel istismar veya sömürü içeriği kesinlikle yasaktır. Cinsel içerik paylaşmayın. Başka kişilerin kimliğine bürünmeyin. Paylaştığınız planın bilgilerini doğru yazın. Uygunsuz plan ve hesapları Şikâyet et seçeneğiyle bildirin; Engelle ile o kişiyle etkileşimi durdurun. Bildirimler uygulama yöneticisi tarafından incelenir; ihlalli içerikler kaldırılabilir ve hesaplar askıya alınabilir.";
 private void showTerms(){new AlertDialog.Builder(this).setTitle("Topluluk kuralları").setMessage(RULES).setPositiveButton("Kapat",null).show();}
 private void acceptTerms(){new AlertDialog.Builder(this).setTitle("Paylaşmadan önce").setMessage(RULES).setNegativeButton("Vazgeç",null).setPositiveButton("Kabul ediyorum",(d,w)->request("POST","/terms/accept",obj("accepted",true),r->{state=r;render();compose();})).show();}
 private void safetyMenu(JSONObject p){String owner=p.optString("user_id");new AlertDialog.Builder(this).setTitle("Plan ve kullanıcı").setItems(new String[]{"Planı şikâyet et","Kullanıcıyı şikâyet et","Kullanıcıyı engelle"},(d,n)->{if(n<2)report(n==0?"plan":"user",n==0?p.optString("id"):owner);else new AlertDialog.Builder(this).setTitle("Kullanıcı engellensin mi?").setMessage("Birbirinizin planlarını göremezsiniz. Aranızdaki takip ve plan katılımı kaldırılır.").setNegativeButton("Vazgeç",null).setPositiveButton("Engelle",(a,b)->request("POST","/block",obj("user_id",owner),r->{state=r;render();msg("Kullanıcı engellendi.");})).show();}).show();}
 private void report(String type,String id){String[] reasons={"Taciz veya tehdit","Nefret söylemi","Spam veya dolandırıcılık","Çocuk güvenliği","Uygunsuz cinsel içerik","Kişisel bilgilerin paylaşılması","Diğer"};new AlertDialog.Builder(this).setTitle("Bildirim nedeni").setItems(reasons,(d,n)->{JSONObject data=obj("target_type",type);try{data.put("target_id",id);data.put("reason",reasons[n]);}catch(Exception ignored){}request("POST","/report",data,r->msg("Bildirimin alındı."));}).setNegativeButton("Vazgeç",null).show();}
 private void showBlocked(){JSONArray users=arr("blocked_users");if(users.length()==0){msg("Engellediğin kişi yok.");return;}String[] names=new String[users.length()];for(int i=0;i<users.length();i++)names[i]=users.optJSONObject(i).optString("name");new AlertDialog.Builder(this).setTitle("Engeli kaldırmak için kişiyi seç").setItems(names,(d,n)->request("POST","/unblock",obj("user_id",users.optJSONObject(n).optString("id")),r->{state=r;render();})).setNegativeButton("Kapat",null).show();}
 private interface Action{void run()throws Exception;}
 private void local(Action a){try{a.run();store.save(state);render();}catch(Exception e){msg("Kayıt yapılamadı: "+e.getMessage());}}
 private JSONObject obj(String k,Object v){JSONObject o=new JSONObject();try{o.put(k,v);}catch(Exception ignored){}return o;}
 private void follow(String id){if(remote){request("POST","/follow",obj("user_id",id),r->{state=r;render();});return;}local(()->state.put("following",Store.toggled(arr("following"),id)));}
 private void join(String id){if(remote){request("POST","/join",obj("plan_id",id),r->{state=r;render();});return;}local(()->state.put("joined",Store.toggled(arr("joined"),id)));}
 private void confirmDelete(String id){new AlertDialog.Builder(this).setTitle("Plan kaldırılsın mı?").setMessage("Bu işlem geri alınamaz.").setNegativeButton("Vazgeç",null).setPositiveButton("Kaldır",(d,w)->{if(remote){request("DELETE","/plans/"+id,null,r->{state=r;render();});return;}local(()->{JSONArray n=new JSONArray();for(int i=0;i<arr("plans").length();i++){JSONObject p=arr("plans").getJSONObject(i);if(!id.equals(p.optString("id")))n.put(p);}state.put("plans",n);});}).show();}
 private EditText field(LinearLayout form,String label,String value,int input,int limit){wide(form,text(label,14,INK,true));EditText e=new EditText(this);e.setText(value);e.setContentDescription(label);e.setTextSize(16);e.setSingleLine(true);e.setInputType(input);e.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(limit)});wide(form,e);gap(form,12);return e;}
 private LinearLayout form(){LinearLayout f=col();f.setPadding(dp(22),dp(14),dp(22),dp(18));return f;}
 private Spinner select(LinearLayout f,String label,String[] values){wide(f,text(label,14,INK,true));Spinner s=new Spinner(this);s.setContentDescription(label);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values));wide(f,s);gap(f,18);return s;}
 private ScrollView formScroll(LinearLayout f){ScrollView s=new ScrollView(this);s.addView(f);return s;}
 private void compose(){if(remote&&!me().optBoolean("terms_accepted")){acceptTerms();return;}LinearLayout f=form();EditText title=field(f,"Ne yapmak istiyorsun?","",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES,100);Spinner type=select(f,"Modun",moods);EditText place=field(f,"Yaklaşık bölge veya çevrimiçi",me().optString("city",""),InputType.TYPE_CLASS_TEXT,60);
  Calendar when=Calendar.getInstance();when.add(Calendar.MINUTE,60);Button time=button(date(when.getTimeInMillis()),0xffe9efdf,()->new DatePickerDialog(this,(v,y,m,d)->{when.set(y,m,d);new TimePickerDialog(this,(tv,h,min)->{when.set(Calendar.HOUR_OF_DAY,h);when.set(Calendar.MINUTE,min);when.set(Calendar.SECOND,0);when.set(Calendar.MILLISECOND,0);},when.get(Calendar.HOUR_OF_DAY),when.get(Calendar.MINUTE),true).show();},when.get(Calendar.YEAR),when.get(Calendar.MONTH),when.get(Calendar.DAY_OF_MONTH)).show());
  // Separate time summary refreshes when the modal regains focus.
  wide(f,text("Tarih ve saat",14,INK,true));wide(f,time);time.setOnClickListener(v->new DatePickerDialog(this,(dv,y,m,d)->new TimePickerDialog(this,(tv,h,min)->{when.set(y,m,d,h,min,0);when.set(Calendar.MILLISECOND,0);time.setText(date(when.getTimeInMillis()));},when.get(Calendar.HOUR_OF_DAY),when.get(Calendar.MINUTE),true).show(),when.get(Calendar.YEAR),when.get(Calendar.MONTH),when.get(Calendar.DAY_OF_MONTH)).show());gap(f,18);
  Spinner audience=select(f,"Kimler görebilsin?",new String[]{"Takipçilerim","Herkes","Yalnızca ben"});wide(f,text("Önümüzdeki 24 saat için plan oluşturabilirsin. Plan, başlangıcından 2 saat sonra veya en geç 24 saatte kapanır.",13,MUTED,false));
  AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Bugünkü modun").setView(formScroll(f)).setNegativeButton("Vazgeç",null).setPositiveButton("Paylaş",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{String t=title.getText().toString().trim(),p=place.getText().toString().trim();long start=when.getTimeInMillis(),now=System.currentTimeMillis();if(t.isEmpty()){title.setError("Bir plan yaz.");return;}if(p.isEmpty()){place.setError("Yaklaşık bölgeyi yaz.");return;}if(start<=now||start>now+86400000L){msg("Önümüzdeki 24 saat içinde bir zaman seç.");return;}try{JSONObject plan=Store.makePlan(me().optString("id"),t,keys[type.getSelectedItemPosition()],p,start,new String[]{"followers","public","private"}[audience.getSelectedItemPosition()]);if(remote){request("POST","/plans",plan,r->{state=r;view="feed";filter="all";dialog.dismiss();render();});}else{local(()->{JSONArray n=new JSONArray().put(plan);for(int i=0;i<arr("plans").length();i++)n.put(arr("plans").get(i));state.put("plans",n);view="feed";filter="all";});dialog.dismiss();msg("Planın telefonuna kaydedildi.");}}catch(Exception e){msg("Plan kaydedilemedi.");}}));dialog.show();}
 private void editProfile(){LinearLayout f=form();EditText name=field(f,"Adın",me().optString("name"),InputType.TYPE_CLASS_TEXT,40);EditText city=field(f,"Şehir",me().optString("city"),InputType.TYPE_CLASS_TEXT,60);AlertDialog d=new AlertDialog.Builder(this).setTitle("Profilin").setView(formScroll(f)).setNegativeButton("Vazgeç",null).setPositiveButton("Kaydet",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String n=name.getText().toString().trim(),c=city.getText().toString().trim();if(n.length()<2){name.setError("En az 2 karakter yaz.");return;}JSONObject data=obj("name",n);try{data.put("city",c);}catch(Exception ignored){}if(remote)request("POST","/profile",data,r->{state=r;d.dismiss();render();});else{local(()->{me().put("name",n);me().put("city",c);});d.dismiss();}}));d.show();}
 private interface Result{void done(JSONObject r)throws Exception;}
 private void request(String method,String path,JSONObject data,Result done){if(busy)return;busy=true;render();String targetBase=base,targetToken=token;io.execute(()->{try{JSONObject r=Api.request(targetBase,targetToken,method,path,data);runOnUiThread(()->{if(isFinishing()||isDestroyed())return;busy=false;try{done.done(r);}catch(Exception e){msg("Yanıt işlenemedi.");}render();});}catch(Exception e){runOnUiThread(()->{if(isFinishing()||isDestroyed())return;busy=false;if(e instanceof Api.Failure&&((Api.Failure)e).status==401&&remote){disconnect();msg("Oturumun sona erdi. Yeniden giriş yap.");}else{render();msg(e.getMessage()==null?"Bağlantı kurulamadı.":e.getMessage());}});}});}
 private void reload(){request("GET","/state",null,r->{state=r;render();});}
 private void logout(){request("POST","/logout",new JSONObject(),r->disconnect());}
 private void disconnect(){session.clear();token="";remote=false;try{state=store.load();}catch(Exception ignored){}view="feed";render();}
 private void authDialog(){LinearLayout f=form();wide(f,text("Gerçek hesaplar için yayımlanmış MOD sunucusu gerekir. Demo verileri hesabına aktarılmaz.",14,MUTED,false));gap(f,14);EditText url=field(f,"MOD sunucu adresi (HTTPS)",base,InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI,250);url.setEnabled(BuildConfig.API_BASE_URL.isEmpty());Spinner mode=select(f,"İşlem",new String[]{"Giriş yap","Yeni hesap oluştur"});EditText name=field(f,"Ad (yeni hesap için)","",InputType.TYPE_CLASS_TEXT,40);EditText email=field(f,"E-posta","",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS,254);EditText password=field(f,"Parola (en az 10 karakter)","",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD,128);
  AlertDialog d=new AlertDialog.Builder(this).setTitle("MOD hesabın").setView(formScroll(f)).setNegativeButton("Vazgeç",null).setPositiveButton("Devam et",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String host=url.getText().toString().trim().replaceAll("/+$","");try{java.net.URI u=new java.net.URI(host);if(!"https".equals(u.getScheme())||u.getHost()==null||u.getUserInfo()!=null||u.getQuery()!=null||u.getFragment()!=null||!(u.getPath()==null||u.getPath().isEmpty()))throw new Exception();}catch(Exception e){url.setError("Örnek: https://api.alanadiniz.com");return;}if(!android.util.Patterns.EMAIL_ADDRESS.matcher(email.getText().toString().trim()).matches()){email.setError("Geçerli bir e-posta yaz.");return;}if(password.length()<10){password.setError("En az 10 karakter gerekli.");return;}boolean register=mode.getSelectedItemPosition()==1;if(register&&name.getText().toString().trim().length()<2){name.setError("Adını yaz.");return;}base=host;JSONObject data=obj("email",email.getText().toString().trim());try{data.put("password",password.getText().toString());data.put("name",name.getText().toString().trim());}catch(Exception ignored){}request("POST",register?"/register":"/login",data,r->{String next=r.getString("token");session.save(next);token=next;remote=true;getPreferences(0).edit().putString("server",base).apply();state=r.getJSONObject("state");view="feed";filter="all";d.dismiss();render();});}));d.show();}
}
